### ISSUE TITLE
Dr. CI bot is triggered on extremely old PRs

### ISSUE THREAD

**Issue by janeyx99** [pytorch/test-infra#668] opened 2022-09-06 22:23 UTC
We should investigate why Dr. CI is being triggered for extremely old PRs. This is a two-sided problem:
- Developers get spammed/can get confused
- This is a waste of resources/tokens for pytorchbot.

Example: https://github.com/pytorch/pytorch/pull/1108#issuecomment-1234658537

**Comment by ZainRizvi** [comment] 2022-09-06 22:32
I wonder if github might randomly be sending us webhook events for old PRs.  There's no other trigger for these comments, right?

Step 1: Validate the assumption. Should add some monitoring to Dr. CI that logs the request which triggers & fires this comment

**Comment by malfet** [comment] 2022-09-06 22:35
Another point Dr.CI should not update comments for closed/merged PRs

**Comment by huydhn** [comment] 2022-09-07 04:50
I think I have been able to get to the bottom of this issue.  This is a subtle error in Dr. CI in which it doesn't honor the owner and the repo values set in the [pull request event](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request) but hardcodes it to `pytorch/pytorch` [here](https://github.com/pytorch/test-infra/blob/main/torchci/lib/bot/drciBot.ts#L49-L54) instead.

Here is what I think happens:

1. pytorch-bot is enabled not only in `pytorch/pytorch`, but also in other repo like `pytorch/torchdynamo`
1. One of us in the [POSSIBLE_USERS](https://github.com/pytorch/test-infra/blob/main/torchci/lib/bot/rolloutUtils.ts#L68-L88) list made a PR in the other repo, for example https://github.com/pytorch/torchdynamo/pull/1108
1. Because pytorch-bot is enabled in dynamo, there was a `pull_request.opened` event associated with https://github.com/pytorch/torchdynamo/pull/1108.  This was the event that triggered Dr. CI and it wasn't come from `pytorch/pytorch` at all, thus the subtlety
1. Dr. CI bot extracted the PR number 1108 and confirmed what the owner of the PR is in the POSSIBLE_USERS list.  It would then posted a new commit in the completely unrelated https://github.com/pytorch/pytorch/pull/1108

The timelines matches (eyeballing):

* 1108:
  * @malfet created a PR on dynamo at `2022-09-01T18:52` https://api.github.com/repos/pytorch/torchdynamo/issues/1108/timeline 
  * The comment on pytorch appeared at `2022-09-01T18:52` https://api.github.com/repos/pytorch/pytorch/issues/1108/timeline
* 1109:
  * @malfet created a PR on dynamo at `2022-09-01T19:01` https://api.github.com/repos/pytorch/torchdynamo/issues/1109/timeline
  * The comment on pytorch appeared at `2022-09-01T19:01` https://api.github.com/repos/pytorch/pytorch/issues/1109/timeline
 
I'm working on a fix for this, so stay tuned:

1. Dr. CI should check for the owner and the repo values of the pull request and only post a comment for `pytorch/pytorch`.  AFAIK, we don't have Dr. CI support for other repos like dynamo yet, do we?
1. Dr. CI should not touch closed/merged PRs

Also, I don't think this is the cause of the API rate limit issue because the frequency of this happening is low.  I only count dozen of occurrences by querying Rockset `issue_comment`

**Comment by kit1980** [comment] 2022-09-07 05:00
@huydhn great investigation!

**Comment by janeyx99** [comment] 2022-09-07 14:12
@huydhn thanks for the detailed digging! And haha I was just passing along the report from other devs 😛

**Closed** 2022-09-07 18:23 UTC
Labels: bug

**Comment by ZainRizvi** [comment] 2022-09-07 18:30
Great detective work @huydh!
